# Generated by gallery/generate.py; do not edit.
function theurgy_gallery:clear
# sal-ammoniac-accumulator: sal ammoniac accumulator static shell
setblock 176 100 176 theurgy:sal_ammoniac_accumulator
# sal-ammoniac-tank: sal ammoniac tank static shell
setblock 180 100 176 theurgy:sal_ammoniac_tank
# incubator-mercury-vessel: incubator mercury vessel static shell
setblock 184 100 176 theurgy:incubator_mercury_vessel
# incubator-sulfur-vessel: incubator sulfur vessel static shell
setblock 176 100 180 theurgy:incubator_sulfur_vessel
# incubator-salt-vessel: incubator salt vessel static shell
setblock 180 100 180 theurgy:incubator_salt_vessel
# stock-control: stone stock rendering control
setblock 184 100 180 minecraft:stone
function theurgy_gallery:verify
