# Generated by gallery/generate.py; do not edit.
execute unless block 176 100 176 theurgy:sal_ammoniac_accumulator run tellraw @a {"text":"gallery mismatch: sal-ammoniac-accumulator","color":"red"}
execute unless block 180 100 176 theurgy:sal_ammoniac_tank run tellraw @a {"text":"gallery mismatch: sal-ammoniac-tank","color":"red"}
execute unless block 184 100 176 theurgy:incubator_mercury_vessel run tellraw @a {"text":"gallery mismatch: incubator-mercury-vessel","color":"red"}
execute unless block 176 100 180 theurgy:incubator_sulfur_vessel run tellraw @a {"text":"gallery mismatch: incubator-sulfur-vessel","color":"red"}
execute unless block 180 100 180 theurgy:incubator_salt_vessel run tellraw @a {"text":"gallery mismatch: incubator-salt-vessel","color":"red"}
execute unless block 184 100 180 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Theurgy gallery checked","color":"green"}
